   # Your request headers, e.g.
    POST http://localhost:8080/reset-password
    Content-Type: application/json

    # The request body, if any
    {
        "passwordResetToken": "rst_f599e7fb-3be2-41c2-863e-0966d059c9b9",
        "newPassword": "This1sMyP@ssword!"
    }